### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flukes86** [CrowdStrike/xwf-yara-scanner#1]
This is amazing thanks for sharing! Do you know if its possible to run multiple yara rules at the same time or wildcard a folder containing multiple yara rules? Many Thanks

**Comment by ctmayhew** [comment]
Hi there, thanks for the kind words! It only accepts one file at the moment. The easiest workaround is to just combine all of the the rules into one file.

**Comment by ctmayhew** [comment]
I will add this as a possible feature for a later version though.

**Comment by forensenellanebbia** [comment]
It'd be great to have this feature implemented. Thanks for sharing this X-Tension.

**Comment by ctmayhew** [comment]
Noted @forensenellanebbia - I'll see what I can do. Glad you are finding this X-Tension useful.

**Comment by ctmayhew** [comment]
@flukes86 the feature to select multiple YARA rules to compile has been implemented and will be in version 1.2.

**Comment by flukes86** [comment]
@ctmayhew - EPIC!!! thank you so much!!! awesome work.

**Comment by ctmayhew** [comment]
This is now in version 1.2

**Comment by rpsirois** [comment]
There is a bit of an asterisk to this. I'm not sure what the maximum number of files is but it's less than hundreds. Or perhaps some combination of total files multiplied by total rules per file.

**Comment by ctmayhew** [comment]
If you have a large dataset, maybe worth compiling them using the official YARA binary first - and then giving the compiled ruleset to the X-Tension.
