### ISSUE TITLE
The two input windows pop up multiple times

### ISSUE THREAD

**Issue by forensenellanebbia** [CrowdStrike/xwf-yara-scanner#3]
I'm trying to use the X-Tension with XWF 20.5 SR-1 x64, but I get prompted multiple times to specify the location of the YARA rule file and the MB/size value. Apparently, the number of times is equal to the number of objects/partitions highlighted in the "Case data window" before running the X-Tension.

**Comment by ctmayhew** [comment]
Hi @forensenellanebbia - I noticed this too a while back. I think it's to do with the code being executed in the XT_Prepare() API call, whereas I should be placing this in the XT_Init() call. Let me see if I can test a fix for you.

**Comment by ctmayhew** [comment]
@forensenellanebbia - I've pushed version 1.1 which fixes this multiple user input issue. Hopefully that works for you. See https://github.com/CrowdStrike/xwf-yara-scanner/tree/main/Compiled%20X-Tensions

**Comment by ctmayhew** [comment]
Fixed in version 1.1

**Comment by forensenellanebbia** [comment]
Awesome, thanks! I tried it and worked perfectly.
