### ISSUE TITLE
Cannot load “C:\Program Files\X-Ways Forensics\x64\XT_Yara.dll”.XT_Init() signals not ready:-1

### ISSUE THREAD

**Issue by SamotZak** [CrowdStrike/xwf-yara-scanner#5]
Hi, I'm trying to use the X-Tension with XWF 20.7 SR-1 x64, but I get an error after I select a file of yara rules: “Cannot load “C:\Program Files\X-Ways Forensics\x64\XT_Yara.dll”.XT_Init() signals not ready:-1".
I tested also versions v.1.1, different yara rules (tested and working with other tools), tried to run on a different forensic machine and got the same error.
![Screenshot x_ways](https://user-images.githubusercontent.com/129489946/229050210-eadb2d36-9ab2-4697-a2dd-0e7db503737c.png)

**Comment by ctmayhew** [comment]
Hi @SamotZak. It looks like you are using the compiled rule file. Can you test with a non-compile ruleset and see if there is the same error?

**Comment by SamotZak** [comment]
> Hi @SamotZak. It looks like you are using the compiled rule file. Can you test with a non-compile ruleset and see if there is the same error?
![Screenshot2](https://user-images.githubusercontent.com/129489946/232721343-c3d69d21-1adb-4013-b59e-41f1b91de607.png)

Hello @ctmayhew, actually the yara ruleset was not compiled. Please find the error of compiled yara rule in the screenshot.

In addition, I'm pretty sure that there was no issue with v.1.0 some time ago.

**Comment by ctmayhew** [comment]
It assumes your rule file is compiled if it ends with .yar or .yara. If you have named your non-compiled ruleset with .yara it will break? Can you check and if so, just end the filename with something else like .txt

**Comment by SamotZak** [comment]
It worked when I changed a file extension to *.txt .

**Comment by ctmayhew** [comment]
Ah good. The new version will assume .yar/yara = compiled and .txt = not compiled. I'll clarify this in the documentation.
