### ISSUE TITLE
Yara version

### ISSUE THREAD

**Issue by dcmattb** [CrowdStrike/xwf-yara-scanner#6]
Hi Chris, would it be possible to update the YARA version again to the latest? This would really help with writing certain rules. Thanks!

**Comment by ctmayhew** [comment]
Hi ! Yes we have a version that uses YARA v4.3.2 internally. I will see if we can push that version to this public repository - this won't be until later on this month though.

**Comment by dcmattb** [comment]
That would be great, thank you! I'll keep an eye out for the update. Cheers!

**Comment by ctmayhew** [comment]
Just pushed a version that uses YARA v4.3.2. You can always re-compile from source if you wanted to use another version in the future, just replace the _libyara_ folder with the latest code.

**Comment by dcmattb** [comment]
Many thanks for that!
