### ISSUE TITLE
Crashing in version  21.2 of X-Ways

### ISSUE THREAD

**Issue by M0x40** [CrowdStrike/xwf-yara-scanner#7]
Using the extension in x-ways version 21.2 during RVS the prompt for max file size displays, but then RVS proceeds before a prompting for the path to the yara rules.  

RVS logs "An exception of type 216 (page protection fault, high or unknown impact, with an X-Tension in control) occurred at offset 7FFD9AADA9C0. The problem was noted in the file "<path to xwf>\error.log"." ,

**Comment by ctmayhew** [comment]
Hi there - I'm not sure why this is the case, but have you tried unchecking the box "Facilitate the use of dependant DLLs"? 
<img width="405" alt="image" src="https://github.com/user-attachments/assets/ada36a52-c981-43fe-9df7-8458c203c7cf">

**Comment by M0x40** [comment]
Confirmed unchecking the "Facilitate use of dependent DLLs" allows the x-tension to run normally.
